name: Code Linting (Detekt)

on:
  push:
    branches-ignore:
      - docs-pages
    
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache gradle dependencies
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Make gradlew executable
        run: chmod +x gradlew
      
      - name: Lint code
        run: ./gradlew detekt
