name: Publish Docs (Dokka)

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
      
      - name: Cache gradle dependencies
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Gradle build docs
        run: |
          chmod +x gradlew
          ./gradlew dokkaHtmlMultiModule
