name: Publish Docs (Dokka)

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
      
      - name: Cache gradle dependencies
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Gradle build docs
        run: |
          chmod +x gradlew
          ./gradlew dokkaHtmlMultiModule
      
      - name: Commit docs to git
        run: |
          git add docs/
          git stash push docs/
          git reset --hard
          git fetch origin docs-pages
          git checkout docs-pages
          git reset c030076 --hard
          git stash pop
          git config user.name "GitHub Actions"
          git config user.email "github-actions@javaman.net"
          git commit -m 'Updated docs'
          git push origin --force
