name: Publish Docs (Dokka)

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate docs
      - run: ./gradlew dokkaHtmlMultiModule

      - name: Add docs to git
      - run: git add *

      - name: Stash docs changes
      - run: git stash push

      - name: Switch to docs-pages branch
      - run: git checkout docs-pages

      - name: Remove previous docs
      - run: rm -rf docs

      - name: Pop docs stash
      - run: git stash pop

      - name: Commit new docs
      - run: git commit -m 'Updated docs'

      - name: Push docs to origin
      - run: git push origin
