name: Tests (Kotlin Multiplatform)

on:
  push:
    branches-ignore:
      - docs-pages
    
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Cache gradle dependencies
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Run tests
        env:
            IBMQ_API_TOKEN: ${{ secrets.IBMQ_API_TOKEN }}
            IBMQ_CODE_ID: ${{ secrets.IBMQ_CODE_ID }}
        run: |
          chmod +x gradlew
          ./gradlew allTests
